name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Copy the .env folder to current working dir
      run: cp /home/dubut/envs/mediahavenfd.env .env
    - name: Build the Docker image
      run: docker build -t mediahavenfd .
    - name: Stop and Remove Existing Container (if running)
      run: docker ps -q --filter "name=mediahavenfd" | grep -q . && docker stop mediahavenfd && docker rm mediahavenfd
    - name: Run the container
      run: docker run -d -p 3000:3000 mediahavenfd mediahavenfd
