name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Create the .env file containing backend server url
      run: echo "REACT_APP_BACKEND_SERVER_URL=http://$(ip -4 addr show wlan0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'):5001" > .env
    - name: Build the Docker image
      run: docker build -t mediahavenfd .
    - name: Stop and Remove Existing Container (if running)
      run: docker ps -q --filter "name=mediahavenfd" | grep -q . && docker stop mediahavenfd && docker rm mediahavenfd || true
    - name: Run the container
      run: docker run -d -p 3000:3000 --restart always mediahavenfd mediahavenfd
